M48
; DRILL file {KiCad 8.0.4-rc2} date 2024-08-04T20:31:59-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-04T20:31:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-rc2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.600
%
G90
G05
T1
X99.847Y-150.266
X225.4Y-151.841
X226.111Y-207.493
T2
X111.165Y-148.336
T3
X137.755Y-150.876
M30
