M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Sun 30 Jun 2024 10:38:20 PM CDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-30T22:38:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.700
%
G90
G05
T1
X88.138Y-62.84
X138.43Y-62.84
T2
X75.184Y-63.5
X132.588Y-119.888
X151.384Y-63.5
X196.875Y-108.509
T0
M30
